-- ========================================
-- Supabase 数据库重构 SQL 脚本
-- 日期：2025-11-24
-- 设计：规范化能力评估数据库（4张表）
-- ========================================

-- ========================================
-- 第一步：删除旧表（如果存在）
-- ⚠️ 警告：这会删除所有现有数据！
-- 请在执行前备份数据
-- ========================================

-- 可选：如果需要保留旧表数据，请注释掉以下DROP语句
-- drop table if exists competency_assessments cascade;
-- drop table if exists competency_definitions cascade;

-- ========================================
-- 第二步：创建新表结构
-- ========================================

-- 1. 部门表
create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,  -- 部门编码（如 SNa-PS, SCh-QA）
  description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table departments is '部门信息表';
comment on column departments.name is '部门名称';
comment on column departments.code is '部门编码（如 SNa-PS）';

-- 2. 员工表
create table if not exists employees (
  id uuid default gen_random_uuid() primary key,
  employee_id text not null unique,  -- 员工工号
  name text not null,                -- 员工姓名
  department_id bigint references departments(id) on delete set null,
  email text,
  position text,                     -- 职位
  is_active boolean default true,    -- 是否在职
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table employees is '员工信息表';
comment on column employees.employee_id is '员工工号（唯一标识）';
comment on column employees.name is '员工姓名';
comment on column employees.department_id is '所属部门ID';

-- 创建索引以提升查询性能
create index idx_employees_department on employees(department_id);
create index idx_employees_employee_id on employees(employee_id);
create index idx_employees_name on employees(name);

-- 3. 技能表（扁平结构，包含模块信息）
create table if not exists skills (
  id bigint generated by default as identity primary key,
  module_id int not null,            -- 模块ID（1-9）
  module_name text not null,         -- 模块名称（如 TPM基础）
  skill_name text not null,          -- 技能名称（如 设备管理）
  skill_code text unique,            -- 技能编码（可选）
  description text,                  -- 技能描述
  display_order int default 0,       -- 显示顺序
  is_active boolean default true,    -- 是否启用
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  -- 确保同一模块下的技能名称唯一
  unique(module_id, skill_name)
);

comment on table skills is '技能定义表（扁平结构）';
comment on column skills.module_id is '模块ID（1=TPM基础, 2=精益流程, ...）';
comment on column skills.module_name is '模块名称';
comment on column skills.skill_name is '技能名称';
comment on column skills.display_order is '显示顺序（用于前端排序）';

-- 创建索引
create index idx_skills_module on skills(module_id);
create index idx_skills_active on skills(is_active);
create index idx_skills_order on skills(display_order);

-- 4. 能力评估表（核心数据表）
create table if not exists competency_assessments (
  id uuid default gen_random_uuid() primary key,
  employee_id uuid references employees(id) on delete cascade not null,
  skill_id bigint references skills(id) on delete cascade not null,
  current_level int not null check (current_level between 1 and 5),  -- 现状得分 C
  target_level int not null check (target_level between 1 and 5),    -- 目标得分 T
  gap int generated always as (target_level - current_level) stored,  -- 差距（自动计算）
  assessment_year int default extract(year from now()),               -- 评估年度
  assessment_date date default current_date,                          -- 评估日期
  notes text,                                                         -- 备注
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  -- 确保同一员工对同一技能在同一年度只有一条记录
  unique(employee_id, skill_id, assessment_year),
  
  -- 约束：目标得分必须 >= 现状得分
  check (target_level >= current_level)
);

comment on table competency_assessments is '能力评估数据表';
comment on column competency_assessments.current_level is '现状得分（1-5）';
comment on column competency_assessments.target_level is '目标得分（1-5）';
comment on column competency_assessments.gap is '差距（自动计算 = 目标 - 现状）';
comment on column competency_assessments.assessment_year is '评估年度';

-- 创建索引以提升查询性能
create index idx_assessments_employee on competency_assessments(employee_id);
create index idx_assessments_skill on competency_assessments(skill_id);
create index idx_assessments_year on competency_assessments(assessment_year);
create index idx_assessments_gap on competency_assessments(gap);

-- ========================================
-- 第三步：创建视图（用于常用查询）
-- ========================================

-- 视图1：完整的评估数据视图（带所有关联信息）
create or replace view view_assessments_full as
select 
  ca.id,
  e.id as employee_id,
  e.employee_id as employee_code,
  e.name as employee_name,
  d.name as department_name,
  d.code as department_code,
  ca.skill_id,
  s.module_id,
  s.module_name,
  s.skill_name,
  s.display_order,
  ca.current_level,
  ca.target_level,
  ca.gap,
  ca.assessment_year,
  ca.assessment_date,
  ca.notes,
  ca.created_at,
  ca.updated_at
from competency_assessments ca
join employees e on e.id = ca.employee_id
left join departments d on d.id = e.department_id
join skills s on s.id = ca.skill_id
where e.is_active = true and s.is_active = true
order by d.name, e.name, s.display_order;

comment on view view_assessments_full is '完整的评估数据视图（包含所有关联信息）';

-- 视图2：员工Gap统计视图
create or replace view view_employee_gaps as
select 
  e.id as employee_id,
  e.employee_id as employee_code,
  e.name as employee_name,
  d.name as department_name,
  ca.assessment_year,
  count(*) as total_skills,                                        -- 总技能数
  count(case when ca.gap > 0 then 1 end) as skills_with_gap,      -- 有差距的技能数
  sum(ca.gap) as total_gap_score,                                  -- 总差距分数
  round(avg(ca.current_level), 2) as avg_current_level,           -- 平均现状得分
  round(avg(ca.target_level), 2) as avg_target_level,             -- 平均目标得分
  round(avg(ca.gap), 2) as avg_gap                                 -- 平均差距
from employees e
left join departments d on d.id = e.department_id
left join competency_assessments ca on ca.employee_id = e.id
where e.is_active = true
group by e.id, e.employee_id, e.name, d.name, ca.assessment_year
order by total_gap_score desc;

comment on view view_employee_gaps is '员工Gap统计视图';

-- 视图3：技能Gap统计视图（按技能统计）
create or replace view view_skill_gaps as
select 
  s.id as skill_id,
  s.module_id,
  s.module_name,
  s.skill_name,
  ca.assessment_year,
  count(distinct ca.employee_id) as total_employees,               -- 评估该技能的员工数
  round(avg(ca.current_level), 2) as avg_current_level,           -- 平均现状得分
  round(avg(ca.target_level), 2) as avg_target_level,             -- 平均目标得分
  round(avg(ca.gap), 2) as avg_gap,                                -- 平均差距
  count(case when ca.gap > 0 then 1 end) as employees_with_gap    -- 有差距的员工数
from skills s
left join competency_assessments ca on s.id = ca.skill_id
where s.is_active = true
group by s.id, s.module_id, s.module_name, s.skill_name, ca.assessment_year
order by avg_gap desc;

comment on view view_skill_gaps is '技能Gap统计视图';

-- 视图4：部门Gap统计视图
create or replace view view_department_gaps as
select 
  d.id as department_id,
  d.name as department_name,
  d.code as department_code,
  ca.assessment_year,
  count(distinct e.id) as total_employees,                         -- 部门员工数
  count(*) as total_assessments,                                   -- 总评估记录数
  sum(ca.gap) as total_gap_score,                                  -- 总差距分数
  round(avg(ca.current_level), 2) as avg_current_level,           -- 平均现状得分
  round(avg(ca.target_level), 2) as avg_target_level,             -- 平均目标得分
  round(avg(ca.gap), 2) as avg_gap                                 -- 平均差距
from departments d
left join employees e on e.department_id = d.id
left join competency_assessments ca on ca.employee_id = e.id
where e.is_active = true
group by d.id, d.name, d.code, ca.assessment_year
order by total_gap_score desc;

comment on view view_department_gaps is '部门Gap统计视图';

-- ========================================
-- 第四步：启用 Row Level Security (RLS)
-- ========================================

alter table departments enable row level security;
alter table employees enable row level security;
alter table skills enable row level security;
alter table competency_assessments enable row level security;

-- 创建公开访问策略（根据实际需求修改）
-- ⚠️ 生产环境请根据实际权限需求调整这些策略

-- 部门表：公开读取
create policy "Public read access on departments" 
  on departments for select using (true);

-- 员工表：公开读取在职员工
create policy "Public read access on active employees" 
  on employees for select using (is_active = true);

-- 技能表：公开读取启用的技能
create policy "Public read access on active skills" 
  on skills for select using (is_active = true);

-- 评估表：公开读取
create policy "Public read access on assessments" 
  on competency_assessments for select using (true);

-- ========================================
-- 第五步：插入初始数据
-- ========================================

-- 插入模块对应的示例技能（根据实际需求调整）
-- 这里只是示例，实际数据请通过导入功能添加

insert into skills (module_id, module_name, skill_name, display_order) values
  (1, 'TPM基础', '设备管理', 1),
  (1, 'TPM基础', '预防维护', 2),
  (1, 'TPM基础', '自主维护', 3),
  (2, '精益流程', 'VSM分析', 4),
  (2, '精益流程', 'SMED', 5),
  (2, '精益流程', '价值流优化', 6),
  (3, '问题解决', '8D方法', 7),
  (3, '问题解决', 'Why-Why分析', 8),
  (3, '问题解决', '根因分析', 9),
  (4, '项目管理', '项目计划', 10),
  (4, '项目管理', '进度管理', 11),
  (4, '项目管理', '风险管理', 12),
  (5, '数据分析', '统计分析', 13),
  (5, '数据分析', 'Excel高级应用', 14),
  (5, '数据分析', '数据可视化', 15),
  (6, '团队领导', '团队建设', 16),
  (6, '团队领导', '沟通协调', 17),
  (6, '团队领导', '冲突管理', 18),
  (7, '质量管理', 'SPC', 19),
  (7, '质量管理', 'FMEA', 20),
  (7, '质量管理', '质量改进', 21),
  (8, '设备管理', '设备选型', 22),
  (8, '设备管理', '设备调试', 23),
  (8, '设备管理', '设备优化', 24),
  (9, '流程优化', '流程分析', 25),
  (9, '流程优化', '流程设计', 26),
  (9, '流程优化', '流程实施', 27)
on conflict (module_id, skill_name) do nothing;

-- ========================================
-- 第六步：创建触发器（自动更新 updated_at）
-- ========================================

-- 创建更新时间戳的函数
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- 为所有表添加触发器
create trigger update_departments_updated_at before update on departments
  for each row execute function update_updated_at_column();

create trigger update_employees_updated_at before update on employees
  for each row execute function update_updated_at_column();

create trigger update_skills_updated_at before update on skills
  for each row execute function update_updated_at_column();

create trigger update_assessments_updated_at before update on competency_assessments
  for each row execute function update_updated_at_column();

-- ========================================
-- 完成！
-- ========================================

-- 查询统计信息
select 'Departments' as table_name, count(*) as row_count from departments
union all
select 'Employees', count(*) from employees
union all
select 'Skills', count(*) from skills
union all
select 'Assessments', count(*) from competency_assessments;

-- 查看视图
select table_name 
from information_schema.views 
where table_schema = 'public' 
  and table_name like 'view_%'
order by table_name;
