-- ========================================
-- Supabase 数据库重构 SQL 脚本 (修复版)
-- 日期：2025-11-24
-- 修复：JOIN条件顺序问题
-- ========================================

-- ⚠️ 如果之前执行失败，请先清理：
-- drop view if exists view_assessments_full;
-- drop view if exists view_employee_gaps;
-- drop view if exists view_skill_gaps;
-- drop view if exists view_department_gaps;
-- drop table if exists competency_assessments cascade;
-- drop table if exists skills cascade;
-- drop table if exists employees cascade;
-- drop table if exists departments cascade;

-- ========================================
-- 第一步：创建表结构
-- ========================================

-- 1. 部门表
create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,
  description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. 员工表
create table if not exists employees (
  id uuid default gen_random_uuid() primary key,
  employee_id text not null unique,
  name text not null,
  department_id bigint references departments(id) on delete set null,
  email text,
  position text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_employees_department on employees(department_id);
create index if not exists idx_employees_employee_id on employees(employee_id);
create index if not exists idx_employees_name on employees(name);

-- 3. 技能表
create table if not exists skills (
  id bigint generated by default as identity primary key,
  module_id int not null,
  module_name text not null,
  skill_name text not null,
  skill_code text unique,
  description text,
  display_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(module_id, skill_name)
);

create index if not exists idx_skills_module on skills(module_id);
create index if not exists idx_skills_active on skills(is_active);
create index if not exists idx_skills_order on skills(display_order);

-- 4. 能力评估表
create table if not exists competency_assessments (
  id uuid default gen_random_uuid() primary key,
  employee_id uuid references employees(id) on delete cascade not null,
  skill_id bigint references skills(id) on delete cascade not null,
  current_level int not null check (current_level between 1 and 5),
  target_level int not null check (target_level between 1 and 5),
  gap int generated always as (target_level - current_level) stored,
  assessment_year int default extract(year from now()),
  assessment_date date default current_date,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(employee_id, skill_id, assessment_year),
  check (target_level >= current_level)
);

create index if not exists idx_assessments_employee on competency_assessments(employee_id);
create index if not exists idx_assessments_skill on competency_assessments(skill_id);
create index if not exists idx_assessments_year on competency_assessments(assessment_year);
create index if not exists idx_assessments_gap on competency_assessments(gap);

-- ========================================
-- 第二步：插入示例技能数据
-- ========================================

insert into skills (module_id, module_name, skill_name, display_order) values
  (1, 'TPM基础', '设备管理', 1),
  (1, 'TPM基础', '预防维护', 2),
  (1, 'TPM基础', '自主维护', 3),
  (2, '精益流程', 'VSM分析', 4),
  (2, '精益流程', 'SMED', 5),
  (2, '精益流程', '价值流优化', 6),
  (3, '问题解决', '8D方法', 7),
  (3, '问题解决', 'Why-Why分析', 8),
  (3, '问题解决', '根因分析', 9),
  (4, '项目管理', '项目计划', 10),
  (4, '项目管理', '进度管理', 11),
  (4, '项目管理', '风险管理', 12),
  (5, '数据分析', '统计分析', 13),
  (5, '数据分析', 'Excel高级应用', 14),
  (5, '数据分析', '数据可视化', 15),
  (6, '团队领导', '团队建设', 16),
  (6, '团队领导', '沟通协调', 17),
  (6, '团队领导', '冲突管理', 18),
  (7, '质量管理', 'SPC', 19),
  (7, '质量管理', 'FMEA', 20),
  (7, '质量管理', '质量改进', 21),
  (8, '设备管理', '设备选型', 22),
  (8, '设备管理', '设备调试', 23),
  (8, '设备管理', '设备优化', 24),
  (9, '流程优化', '流程分析', 25),
  (9, '流程优化', '流程设计', 26),
  (9, '流程优化', '流程实施', 27)
on conflict (module_id, skill_name) do nothing;

-- ========================================
-- 第三步：创建视图（修复JOIN顺序）
-- ========================================

-- 视图1：完整评估数据视图
create or replace view view_assessments_full as
select 
  ca.id,
  e.id as employee_id,
  e.employee_id as employee_code,
  e.name as employee_name,
  d.name as department_name,
  d.code as department_code,
  ca.skill_id,
  s.module_id,
  s.module_name,
  s.skill_name,
  s.display_order,
  ca.current_level,
  ca.target_level,
  ca.gap,
  ca.assessment_year,
  ca.assessment_date,
  ca.notes,
  ca.created_at,
  ca.updated_at
from competency_assessments ca
join employees e on e.id = ca.employee_id
left join departments d on d.id = e.department_id
join skills s on s.id = ca.skill_id
where e.is_active = true and s.is_active = true
order by d.name, e.name, s.display_order;

-- 视图2：员工Gap统计
create or replace view view_employee_gaps as
select 
  e.id as employee_id,
  e.employee_id as employee_code,
  e.name as employee_name,
  d.name as department_name,
  coalesce(ca.assessment_year, extract(year from now())::int) as assessment_year,
  count(ca.id) as total_skills,
  count(case when ca.gap > 0 then 1 end) as skills_with_gap,
  coalesce(sum(ca.gap), 0) as total_gap_score,
  round(avg(ca.current_level), 2) as avg_current_level,
  round(avg(ca.target_level), 2) as avg_target_level,
  round(avg(ca.gap), 2) as avg_gap
from employees e
left join departments d on d.id = e.department_id
left join competency_assessments ca on ca.employee_id = e.id
where e.is_active = true
group by e.id, e.employee_id, e.name, d.name, ca.assessment_year
order by total_gap_score desc;

-- 视图3：技能Gap统计
create or replace view view_skill_gaps as
select 
  s.id as skill_id,
  s.module_id,
  s.module_name,
  s.skill_name,
  coalesce(ca.assessment_year, extract(year from now())::int) as assessment_year,
  count(distinct ca.employee_id) as total_employees,
  round(avg(ca.current_level), 2) as avg_current_level,
  round(avg(ca.target_level), 2) as avg_target_level,
  round(avg(ca.gap), 2) as avg_gap,
  count(case when ca.gap > 0 then 1 end) as employees_with_gap
from skills s
left join competency_assessments ca on ca.skill_id = s.id
where s.is_active = true
group by s.id, s.module_id, s.module_name, s.skill_name, ca.assessment_year
order by avg_gap desc;

-- 视图4：部门Gap统计
create or replace view view_department_gaps as
select 
  d.id as department_id,
  d.name as department_name,
  d.code as department_code,
  coalesce(ca.assessment_year, extract(year from now())::int) as assessment_year,
  count(distinct e.id) filter (where e.is_active) as total_employees,
  count(ca.id) as total_assessments,
  coalesce(sum(ca.gap), 0) as total_gap_score,
  round(avg(ca.current_level), 2) as avg_current_level,
  round(avg(ca.target_level), 2) as avg_target_level,
  round(avg(ca.gap), 2) as avg_gap
from departments d
left join employees e on e.department_id = d.id
left join competency_assessments ca on ca.employee_id = e.id
group by d.id, d.name, d.code, ca.assessment_year
order by total_gap_score desc;

-- ========================================
-- 第四步：启用RLS
-- ========================================

alter table departments enable row level security;
alter table employees enable row level security;
alter table skills enable row level security;
alter table competency_assessments enable row level security;

create policy if not exists "Public read on departments" 
  on departments for select using (true);

create policy if not exists "Public read on active employees" 
  on employees for select using (is_active = true);

create policy if not exists "Public read on active skills" 
  on skills for select using (is_active = true);

create policy if not exists "Public read on assessments" 
  on competency_assessments for select using (true);

-- ========================================
-- 第五步：创建触发器
-- ========================================

create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists update_departments_updated_at on departments;
create trigger update_departments_updated_at before update on departments
  for each row execute function update_updated_at_column();

drop trigger if exists update_employees_updated_at on employees;
create trigger update_employees_updated_at before update on employees
  for each row execute function update_updated_at_column();

drop trigger if exists update_skills_updated_at on skills;
create trigger update_skills_updated_at before update on skills
  for each row execute function update_updated_at_column();

drop trigger if exists update_assessments_updated_at on competency_assessments;
create trigger update_assessments_updated_at before update on competency_assessments
  for each row execute function update_updated_at_column();

-- ========================================
-- 完成！查看统计
-- ========================================

select 'Tables created:' as status;
select 'Departments' as table_name, count(*) as row_count from departments
union all
select 'Employees', count(*) from employees
union all
select 'Skills', count(*) from skills
union all
select 'Assessments', count(*) from competency_assessments;

select 'Views created:' as status;
select table_name 
from information_schema.views 
where table_schema = 'public' 
  and table_name like 'view_%'
order by table_name;
