-- ============================================================================
-- 资源规划模块数据库Schema
-- Resource Planning Module Database Schema
-- ============================================================================
-- 创建日期: 2025-11-24
-- 说明: 独立的资源规划表结构，用于存储Excel导入的任务数据
-- 特性: 追加模式、版本追踪、最新状态显示
-- ============================================================================

-- ============================================================================
-- 1. 资源规划任务类型表 (Resource Task Types)
-- ============================================================================
-- 说明: 存储Excel中的任务类型映射（颜色+缩写）
-- 特点: 独立于Schedule模块的task_types表
CREATE TABLE IF NOT EXISTS resource_task_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,        -- 缩写代码 (如: "WS", "P", "T")
  name TEXT NOT NULL,               -- 完整名称
  color_hex TEXT NOT NULL,          -- 十六进制颜色 (高可读性)
  description TEXT,                 -- 描述
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 添加注释
COMMENT ON TABLE resource_task_types IS '资源规划任务类型配置表';
COMMENT ON COLUMN resource_task_types.code IS '任务类型缩写代码 (用于Excel解析)';
COMMENT ON COLUMN resource_task_types.color_hex IS '任务类型颜色 (十六进制)';

-- ============================================================================
-- 2. 资源规划任务表 (Resource Planning Tasks)
-- ============================================================================
-- 说明: 存储从Excel导入的实际任务数据
-- 特点: 支持合并单元格（跨周任务）、版本追踪、追加模式
CREATE TABLE IF NOT EXISTS resource_planning_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- 关联关系
  employee_id UUID REFERENCES employees(id) NOT NULL,
  task_type_code TEXT NOT NULL,     -- 直接存储代码，便于快速查询
  
  -- 时间范围（关键：处理合并单元格）
  start_week TEXT NOT NULL,         -- Excel原始周数 "CW23"
  end_week TEXT NOT NULL,           -- Excel原始周数 "CW25"
  start_date DATE NOT NULL,         -- 计算出的开始日期
  end_date DATE NOT NULL,           -- 计算出的结束日期
  
  -- 任务详情
  topic TEXT,                       -- Excel单元格中的具体文字（可选）
  location TEXT,                    -- 任务地点（可选）
  notes TEXT,                       -- 备注信息
  
  -- 版本追踪（关键：支持追加和显示最新）
  imported_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),  -- 导入时间戳（判断最新）
  import_batch_id UUID,             -- 同一次导入的批次ID
  source_file_name TEXT,            -- 来源Excel文件名
  
  -- 元数据
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 添加注释
COMMENT ON TABLE resource_planning_tasks IS '资源规划任务数据表';
COMMENT ON COLUMN resource_planning_tasks.start_week IS 'Excel原始周数格式 (如: CW23)';
COMMENT ON COLUMN resource_planning_tasks.end_week IS 'Excel原始周数格式 (如: CW25)，支持合并单元格';
COMMENT ON COLUMN resource_planning_tasks.imported_at IS '导入时间戳，用于判断最新版本';
COMMENT ON COLUMN resource_planning_tasks.import_batch_id IS '批次ID，用于追踪同一次导入的所有任务';

-- ============================================================================
-- 3. 索引优化
-- ============================================================================
-- 提高查询性能

-- 按员工查询（最常用）
CREATE INDEX IF NOT EXISTS idx_resource_tasks_employee 
  ON resource_planning_tasks(employee_id);

-- 按日期范围查询
CREATE INDEX IF NOT EXISTS idx_resource_tasks_dates 
  ON resource_planning_tasks(start_date, end_date);

-- 按导入时间排序（获取最新版本）
CREATE INDEX IF NOT EXISTS idx_resource_tasks_imported_at 
  ON resource_planning_tasks(imported_at DESC);

-- 按批次查询
CREATE INDEX IF NOT EXISTS idx_resource_tasks_batch 
  ON resource_planning_tasks(import_batch_id);

-- 按任务类型查询
CREATE INDEX IF NOT EXISTS idx_resource_tasks_type 
  ON resource_planning_tasks(task_type_code);

-- 复合索引：员工+时间（高频查询）
CREATE INDEX IF NOT EXISTS idx_resource_tasks_emp_date 
  ON resource_planning_tasks(employee_id, start_date, end_date);

-- ============================================================================
-- 4. 触发器：自动更新时间戳
-- ============================================================================
CREATE OR REPLACE FUNCTION update_resource_task_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_resource_task_timestamp ON resource_planning_tasks;
CREATE TRIGGER trigger_update_resource_task_timestamp
  BEFORE UPDATE ON resource_planning_tasks
  FOR EACH ROW
  EXECUTE FUNCTION update_resource_task_timestamp();

-- ============================================================================
-- 5. 视图：获取最新版本的任务
-- ============================================================================
-- 说明: 这个视图自动筛选出每个员工+时间段的最新任务版本
CREATE OR REPLACE VIEW view_resource_planning_latest AS
WITH ranked_tasks AS (
  SELECT 
    rpt.*,
    rtt.name AS task_type_name,
    rtt.color_hex AS task_type_color,
    e.name AS employee_name,
    e.employee_id AS employee_code,
    d.name AS department_name,
    ROW_NUMBER() OVER (
      PARTITION BY rpt.employee_id, rpt.start_week, rpt.end_week, rpt.task_type_code
      ORDER BY rpt.imported_at DESC
    ) AS rn
  FROM resource_planning_tasks rpt
  LEFT JOIN resource_task_types rtt ON rpt.task_type_code = rtt.code
  LEFT JOIN employees e ON rpt.employee_id = e.id
  LEFT JOIN departments d ON e.department_id = d.id
)
SELECT 
  id,
  employee_id,
  employee_name,
  employee_code,
  department_name,
  task_type_code,
  task_type_name,
  task_type_color,
  start_week,
  end_week,
  start_date,
  end_date,
  topic,
  location,
  notes,
  imported_at,
  import_batch_id,
  source_file_name,
  created_at,
  updated_at
FROM ranked_tasks
WHERE rn = 1;

COMMENT ON VIEW view_resource_planning_latest IS '资源规划最新版本任务视图';

-- ============================================================================
-- 6. RLS安全策略
-- ============================================================================
-- 启用行级安全
ALTER TABLE resource_task_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE resource_planning_tasks ENABLE ROW LEVEL SECURITY;

-- 任务类型表：所有认证用户可读
DROP POLICY IF EXISTS "Allow authenticated users to read resource_task_types" ON resource_task_types;
CREATE POLICY "Allow authenticated users to read resource_task_types"
  ON resource_task_types FOR SELECT
  TO authenticated
  USING (true);

-- 任务表：所有认证用户可读
DROP POLICY IF EXISTS "Allow authenticated users to read resource_planning_tasks" ON resource_planning_tasks;
CREATE POLICY "Allow authenticated users to read resource_planning_tasks"
  ON resource_planning_tasks FOR SELECT
  TO authenticated
  USING (true);

-- 任务表：所有认证用户可插入（导入功能）
DROP POLICY IF EXISTS "Allow authenticated users to insert resource_planning_tasks" ON resource_planning_tasks;
CREATE POLICY "Allow authenticated users to insert resource_planning_tasks"
  ON resource_planning_tasks FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- 任务表：所有认证用户可更新
DROP POLICY IF EXISTS "Allow authenticated users to update resource_planning_tasks" ON resource_planning_tasks;
CREATE POLICY "Allow authenticated users to update resource_planning_tasks"
  ON resource_planning_tasks FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- 7. 预设任务类型数据（高可读性颜色）
-- ============================================================================
-- 说明: 基于Excel常见任务类型，使用高对比度、易区分的颜色
INSERT INTO resource_task_types (code, name, color_hex, description) VALUES
  ('WS', 'Workshop', '#3B82F6', '研讨会/工作坊 - 蓝色'),
  ('SW', 'Speed Week', '#8B5CF6', '快速周改善活动 - 紫色'),
  ('P', 'Project', '#10B981', '项目实施 - 绿色'),
  ('T', 'Training', '#F59E0B', '培训课程 - 橙色'),
  ('C', 'Coaching', '#EF4444', '辅导指导 - 红色'),
  ('M', 'Meeting', '#6366F1', '会议 - 靛蓝色'),
  ('L', 'Leave', '#64748B', '休假 - 灰色'),
  ('SD', 'Self-Develop', '#14B8A6', '自我发展 - 青色'),
  ('A', 'Assessment', '#EC4899', '评估审核 - 粉色'),
  ('S', 'Support', '#06B6D4', '现场支持 - 天蓝色'),
  ('O', 'Others', '#9CA3AF', '其他 - 浅灰色')
ON CONFLICT (code) DO NOTHING;

-- ============================================================================
-- 8. 辅助函数：周数转日期
-- ============================================================================
-- 说明: 将 "CW23" 格式转换为日期
-- 示例: week_to_date('CW23', 2025) -> '2025-06-02'
CREATE OR REPLACE FUNCTION week_to_date(week_str TEXT, year INT DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INT)
RETURNS DATE AS $$
DECLARE
  week_num INT;
BEGIN
  -- 提取周数（去掉"CW"前缀）
  week_num := SUBSTRING(week_str FROM 3)::INT;
  
  -- 计算该年第一周的开始日期，然后加上相应的周数
  RETURN DATE_TRUNC('week', MAKE_DATE(year, 1, 4)) + (week_num - 1) * INTERVAL '1 week';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION week_to_date IS '将CW格式周数转换为日期';

-- ============================================================================
-- 9. 辅助函数：批量插入助手
-- ============================================================================
-- 说明: 用于批量插入任务时自动生成批次ID
CREATE OR REPLACE FUNCTION generate_import_batch_id()
RETURNS UUID AS $$
BEGIN
  RETURN gen_random_uuid();
END;
$$ LANGUAGE plpgsql VOLATILE;

-- ============================================================================
-- 10. 验证数据完整性
-- ============================================================================
-- 添加约束：确保周数格式正确
ALTER TABLE resource_planning_tasks 
  ADD CONSTRAINT check_week_format 
  CHECK (start_week ~ '^CW\d{1,2}$' AND end_week ~ '^CW\d{1,2}$');

-- 添加约束：结束日期不能早于开始日期
ALTER TABLE resource_planning_tasks 
  ADD CONSTRAINT check_date_order 
  CHECK (end_date >= start_date);

-- ============================================================================
-- 完成提示
-- ============================================================================
DO $$
BEGIN
  RAISE NOTICE '✅ Resource Planning Database Schema Created Successfully!';
  RAISE NOTICE '📊 Tables: resource_task_types, resource_planning_tasks';
  RAISE NOTICE '🔍 View: view_resource_planning_latest';
  RAISE NOTICE '🎨 Preset Task Types: 11 types with high-readability colors';
  RAISE NOTICE '🔐 RLS Policies: Enabled for authenticated users';
  RAISE NOTICE '⚡ Indexes: Created for performance optimization';
  RAISE NOTICE '';
  RAISE NOTICE '📝 Next Steps:';
  RAISE NOTICE '   1. Run this SQL in Supabase SQL Editor';
  RAISE NOTICE '   2. Update TypeScript types in database.types.ts';
  RAISE NOTICE '   3. Extend supabaseService.ts with API methods';
  RAISE NOTICE '   4. Create Excel parser utility';
  RAISE NOTICE '   5. Build Resource Planning Import UI';
END $$;
